# AI-ASSISTED: Generated by Claude Code (Claude Opus 5.5) from prompt "repo cleanup, add tests".
# Reviewed and verified by [reviewer to complete before merge] on [date].
# Verification: passes in CI; checked by mutation (tests fail against deliberately broken code).
from __future__ import annotations

import numpy as np
import pytest
import xarray as xr

from aliprocessing.l2.forwardmodel import _aolp, _dolp, _q

TRANSFORMS = [_dolp, _aolp, _q]


def _stokes_dataset(radiance: np.ndarray, wf: np.ndarray) -> xr.Dataset:
    """
    Builds a dataset with the same layout as the SASKTRAN2 output used by ALIForwardModel

    radiance has shape (spectral_grid, los, stokes) and wf has shape (x, spectral_grid, los, stokes)
    """
    return xr.Dataset(
        {
            "radiance": (["spectral_grid", "los", "stokes"], radiance),
            "wf": (["x", "spectral_grid", "los", "stokes"], wf),
        }
    )


@pytest.fixture
def linear_model():
    """
    Stokes radiances that depend linearly on a state vector x, so the exact Jacobian is known
    """
    rng = np.random.default_rng(0)
    nx, nwav, nlos = 3, 2, 4

    base = np.empty((nwav, nlos, 3))
    base[..., 0] = rng.uniform(1.0, 2.0, size=(nwav, nlos))
    base[..., 1:] = rng.uniform(0.1, 0.5, size=(nwav, nlos, 2))
    jacobian = rng.normal(scale=0.1, size=(nx, nwav, nlos, 3))

    def at(x: np.ndarray) -> xr.Dataset:
        return _stokes_dataset(
            base + np.einsum("k...,k->...", jacobian, x), jacobian.copy()
        )

    return nx, at


def test_known_values():
    # I = 2, Q = 1, U = 1
    rad = _stokes_dataset(
        np.array([2.0, 1.0, 1.0]).reshape(1, 1, 3), np.zeros((1, 1, 1, 3))
    )

    np.testing.assert_allclose(_dolp(rad)[0], np.sqrt(2) / 2)
    np.testing.assert_allclose(_aolp(rad)[0], np.pi / 8)
    np.testing.assert_allclose(_q(rad)[0], 0.5)


def test_unpolarized_light():
    rad = _stokes_dataset(
        np.array([2.0, 0.0, 1e-12]).reshape(1, 1, 3), np.zeros((1, 1, 1, 3))
    )

    np.testing.assert_allclose(_dolp(rad)[0], 0.0, atol=1e-12)
    np.testing.assert_allclose(_q(rad)[0], 0.0)


@pytest.mark.parametrize("transform", TRANSFORMS)
def test_jacobian_matches_finite_difference(transform, linear_model):
    nx, at = linear_model
    _, analytic = transform(at(np.zeros(nx)))

    h = 1e-6
    for k in range(nx):
        step = np.zeros(nx)
        step[k] = h
        fd = (transform(at(step))[0] - transform(at(-step))[0]) / (2 * h)

        np.testing.assert_allclose(
            analytic.isel(x=k).transpose("spectral_grid", "los").to_numpy(),
            fd.transpose("spectral_grid", "los").to_numpy(),
            rtol=1e-6,
            atol=1e-9,
        )


@pytest.mark.parametrize("transform", [_dolp, _q])
def test_jacobian_layout_matches_forward_model_assignment(transform, linear_model):
    # ALIForwardModel.calculate_radiance writes these directly into a numpy array of shape
    # (x, spectral_grid, los) without transposing, so the dimension order must not change
    nx, at = linear_model

    value, wf = transform(at(np.zeros(nx)))

    assert value.dims == ("spectral_grid", "los")
    assert wf.dims == ("x", "spectral_grid", "los")


def test_aolp_jacobian_can_be_transposed_to_forward_model_layout(linear_model):
    nx, at = linear_model

    value, wf = _aolp(at(np.zeros(nx)))

    assert value.dims == ("spectral_grid", "los")
    assert set(wf.dims) == {"x", "spectral_grid", "los"}
